#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Please provide exactly two arguments"
    echo "Usage: run-local /path/local \"php -v\""
    exit 1
fi

MOUNT=$1
COMMAND=$2

docker run -it \
  --rm \
  --name php-with-ffi \
  -v "$MOUNT":/var/www:delegated \
  rechtlogisch/php-with-ffi:"${IMAGE_TAG:-latest}" \
  $COMMAND
