name: Publish images

on: [workflow_dispatch]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tag: ['8.1-rc-cli', '8.0-cli', '7.4-cli']

    name: PHP ${{ matrix.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          build-args: |
            "IMAGE_TAG=${{ matrix.tag }}"
          cache-from: type=registry,ref=rechtlogisch/php-with-ffi:${{ matrix.tag }}
          cache-to: type=inline
          tags: rechtlogisch/php-with-ffi:${{ matrix.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
